### ISSUE TITLE
Pipe returns dst?

### ISSUE THREAD

**Issue by Izhaki** [substack/stream-handbook#70]
The doc says:

".pipe(dst) returns dst so that you can chain together multiple .pipe() calls together:"

Is this right?

Shouldn't it read ".pipe(dst) returns **src**..."?

If the format is:

    src.pipe(dst)

And the example given is:

    a.pipe(b).pipe(c).pipe(d)

Which is compared to:

    a.pipe(b);
    b.pipe(c);
    c.pipe(d);

Then all these follow the `src.pipe(dst)` and not `dst.pipe(dst)`.

**Comment by Marsup** [comment]
This is correct, pipe returns its argument. The example is correct as well.

**Comment by undoZen** [comment]
pipe returns dst, which could be used as another to-be-piped stream's src
